# Generated by Django 5.2.4 on 2025-07-21 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("face_app", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="FaceAppModel",
        ),
    ]
